### ISSUE TITLE
Components always get mounted when out of view

### ISSUE THREAD

**Issue by jackkitley** [RadKod/v-lazy-component#64]
Thanks for the plugin.

Im lazy loading multiple components but they all load in on dom render.

![Screenshot 2023-08-28 at 15 26 46](https://github.com/selimdoyranli/v-lazy-component/assets/3243014/7922fd9f-6e8e-4f45-b6a4-ffcd387d2dae)
![Screenshot 2023-08-28 at 15 26 54](https://github.com/selimdoyranli/v-lazy-component/assets/3243014/c07ac4b7-c250-44ba-8f23-448377001e35)

**Comment by selimdoyranli** [comment]
i just tried it and it doesn't seem to be a problem. Also the multiple render issue can't be possible because there is an example with multiple lazy components in the [demo](https://v-lazy-component.vercel.app/demo). there I would have noticed it.  Please make sure that lazy components are not in the viewport at the same time. Also check values like thereshold, rootMargin. I'm closing this issue for now, ping me again in any case.

**Comment by jackkitley** [comment]
@selimdoyranli thanks for the feedback. So I got it right in the end. The components were for a brief moment all in view and then they expanded. So for that quick moment it was in view.

So what I did was set a style min height on the lazy-component and this prevented them all from being collapsed in the beginning.

**Comment by jackkitley** [comment]
The props for the lazy component didn't seem to help. Root margin and threshold
